### ISSUE TITLE
Feature Request: Apprise API Plugin

### ISSUE THREAD

**Issue by Zottelchen** [Qolors/FeedCord#10]
For some feeds, I like to send them to multiple platforms at once (typically Pushover, ntfy & Discord). It would be great to have this functionality here. 

The probably easiest way to support a lot of different services would be supporting the Apprise API (https://github.com/caronc/apprise / https://hub.docker.com/r/caronc/apprise / https://github.com/caronc/apprise-api). This way users could add this service to their docker-compose.yaml if they need it, but would otherwise be unbothered by it.

**Comment by Qolors** [comment]
Hey awesome idea.. let me do some testing - some configuration in the code can definitely make this doable while running the apprise api alongside feedcord in the docker compose yaml file. 

Thanks for sharing - keep you posted!

**Comment by Qolors** [comment]
Where FeedCord is at right now, this doesn't fit the current scope. I will backlog this feature for future reference
