### ISSUE TITLE
Reddit RSS feed not working

### ISSUE THREAD

**Issue by MrGoodGuy2144** [Qolors/FeedCord#12]
When trying to use https://www.reddit.com/r/CrackWatch.rss or https://www.reddit.com/r/CrackWatch 

Both do not work and give an error. Maybe i need to use a different feed url or support needs to be added? Any suggestions?
![rss](https://github.com/Qolors/FeedCord/assets/58582841/64914550-9161-4feb-8811-b3f8ca153d2a)

**Comment by Qolors** [comment]
Did the url with the appending .rss ever work at all? If so could be reddit rate limiting, though not too familiar with reddits newer policies..

If not it could simply be a parsing issue on FeedCord's end.. 

I'll mark it as a bug for now - expect an update within the next couple days. Cheers!

**Comment by MrGoodGuy2144** [comment]
I just started using FeedCord yesterday but other RSS feeds appeared to to work, but not Reddit. Reddit does appear to do it a little different, at least from the user side. When i go to https://www.reddit.com/r/CrackWatch.rss it downloads the RSS feed instead of displaying it in my browser like other feeds Ive used. Could be a parsing error like you mentioned. thanks!

**Comment by Qolors** [comment]
@MrGoodGuy2144 Apologies for the wait - The newest image should better support Reddit feeds. Closing the issue - please reopen if there are any issues. Thanks!
