### ISSUE TITLE
Failed to update discord forum after feed got updated.

### ISSUE THREAD

**Issue by kutsaratinidor** [Qolors/FeedCord#15]
I was expecting a new post to trigger feedcord but somehow there was no post. The feed was used in two different instances with their own respective discord webhooks, but neither worked. I checked the logs and it didnt show any new entry even though it was updated. It only worked once last week. Other test feed that I have active work except for this one

Feed was from this https://anchor.fm/s/4555b94c/podcast/rss

**Comment by kutsaratinidor** [comment]
@Qolors thanks. pulled the latest image and will see when the feed gets updated. Is there actually a way to trigger a post manually?

**Comment by Qolors** [comment]
@kutsaratinidor Hey there,

Could you please repull the image? There was a nightly testing image that was pushed to latest by accident - terrible mistake by me. You may notice it continually posting whether it's new or not. I have just pushed a corrected image.

No way to trigger a post manually yet, though in the works of a web UI to handle these kinds of things.

Terribly sorry about the mistake again - cheers
