### ISSUE TITLE
Post more than one newer post per feed if available

### ISSUE THREAD

**Issue by MrGoodGuy2144** [Qolors/FeedCord#16]
Hello, maybe i am using FeedCord/Discord incorrectly but i was wondering if there was a way to prevent the same feed post from being posted multiple times in discord.

For an example when i have "RssCheckIntervalMinutes":  set to 1 it will post the same duplicate post every 1 minute until there is a new post and then keep posting that. 

Instead i would still like it to check every 1 minute for new posts on the RSS feed, but only post new content instead of the same post every time. This would make it so the rss feed is always up-to-date and you are not spammed with the same post from the feed.

Realistically i wanna check every 15-30 mins but still the same issue remains of duplicate posts. thanks!

![image](https://github.com/Qolors/FeedCord/assets/58582841/f44e4cf1-3d93-4a34-a55f-d2258224c774)

**Comment by Qolors** [comment]
Hey @MrGoodGuy2144! Terribly sorry but this was an error on my end.

Please re-pull the feedcord:latest image and it will fix this issue. Last night my 'nightly' image was pushed as the latest by mistake.

Again, terribly sorry for the trouble!

**Comment by MrGoodGuy2144** [comment]
No worries, Unfortunately now when i start FeedCord it tests successfully for 1/1 urls but does not find any new posts. I tried this for a few different feeds, some i never tried before just in case. Wasnt getting any new posts for any feed or any msg in discord.

![image](https://github.com/Qolors/FeedCord/assets/58582841/5831cc31-c32f-4c4e-b946-aad695c48b06)

**Comment by MrGoodGuy2144** [comment]
Okay after further testing with a more active RSS feed it looks to work with only new posts after the bot has been started. I guess that makes sense, just wanted to confirm that expected behavior? 

I figured that upon starting the bot it would post to discord the latest post on the feed and then wait and check intervals for any new updates, instead now not posting anything to discord until a new post on feed. This was noticeable for me because trying new feeds i cannot tell if they work or not until i leave them for a few hours until a new post is on the feed.

Sorry if i am being confusing!

**Comment by MrGoodGuy2144** [comment]
A web UI would be helpful!! I was wondering if lets say you have a interval of 1 minute, but there are multiple new posts added to the feed within that minute, it will only show last post in the discord correct? Is there a way to send all the new posts from the updated rss feed, not just the last one?

I just noticed one feed i used was missing some items in discord due to having more than 1 post in the feed per minute.

**Comment by Qolors** [comment]
I'll open this back up as a feature request - not a bad idea. Next patch should have it implemented 👍

**Comment by MrGoodGuy2144** [comment]
Great to hear! This would also be helpful for say you have an interval of 12 hours, and you know there will be a few posts within those hours, but its not important to grab them every hour. This allows you to set larger intervals without losing multiple posts! (Might be helpful in some cases of rate limiting?)

 Maybe an option to limit the amount of new posts to grab? e.g only newest/last five/all/#. Maybe also configurable on each instance? Just some suggestions :)

**Comment by Qolors** [comment]
Multiple new posts per RSS Feed & Respecting the Rate Limit is now handled in the newest version [2.1.0](https://github.com/Qolors/FeedCord/releases/tag/v2.1.0)

Configurations for this may be down the road - thanks for the input!
