### ISSUE TITLE
UserName is non optional for channels

### ISSUE THREAD

**Issue by pyamsoft** [Qolors/FeedCord#17]
Just letting you know that when following the v2 config with Forum:false, the docs list Username as an optional field, but the Discord API rejects webhooks posts if a Username is not defined.

In the Notifier code, a missing username falls back to a blank string instead of a defined name, like `FeedCord` so if the appsettings does not define a Username, the webhooks post appears to fail with a 400 status. 

I believe the docs should be updated, or a valid fallback username should be provided by the notifier.

**Comment by Qolors** [comment]
Nice catch! I'll be sure to correct this in the coming update. Thanks 👍

**Comment by Qolors** [comment]
A proper fallback has been added in the recent update [v2.1.0](https://github.com/Qolors/FeedCord/releases/tag/v2.1.0)
