### ISSUE TITLE
Youtube URL can't be null

### ISSUE THREAD

**Issue by LilDrunkenSmurf** [Qolors/FeedCord#2]
Trying to set this up, as I just want to pull `atom` feeds from github to discord, however it won't let me skip `YoutubeUrls`.

I tried adding a blank value, and still get the same error:
```
 Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'youtubeurls')
```

This is a sanitized version of my `appsettings.json`:
```
        {
          "RssURLS": [
            "https://github.com/Qolors/FeedCord/commits/main/.atom",
          ],
          "DiscordWebhookUrl": "https://discord.com/api/webhooks/<token>",
          "RssCheckIntervalMinutes": 10,
          "AuthorName": "Feedcord"
        }
```

I tried adding just a blank value, like this: `"YoutubeUrls": [""],` and it still had errors parsing the URLS. I had to add in a proper youtube URL for it to work at all, but I don't really want to be notified about any youtube updates. Is there a way to make this be optional?

**Comment by allenbilly12** [comment]
Great work! but yes I second @LilDrunkenSmurf. Will be keeping an eye out for the new release.

**Comment by LilDrunkenSmurf** [comment]
Wonderful. I'll have a follow up request shortly 🤣

**Comment by Qolors** [comment]
@LilDrunkenSmurf @allenbilly12 

First off, apologies for the delay as I wasn't able to get to it last night..

This should be handled correctly now with the latest image - leaving the YoutubeUrls array with an empty string will now skip the Youtube Urls. You can view an example [here](https://github.com/Qolors/FeedCord/releases/tag/v1.2.1) in the latest release.

Thanks for your patience and if you have any additional issues or requests please feel free to open another issue! 👍
