### ISSUE TITLE
Unable to parse specific RSS feed

### ISSUE THREAD

**Issue by MrGoodGuy2144** [Qolors/FeedCord#22]
Hello, 

I believe i have found another case of Feedcord being unable to process a specific RSS feed.

URL: https://www.thestar.com/search/?f=rss&t=article&c=news/canada*&l=50&s=start_time&sd=desc

I assume it probably has to do with this part"?f=rss&t=article&c=news/canada*&l=50&s=start_time&sd=desc" of the URL and how it sorta has the search query syntax at the end or whatever.

Here is the websites RSS feed list to compare other urls. https://www.thestar.com/site/static-pages/rss-feeds.html

Thanks

**Comment by Qolors** [comment]
Hey there are you receiving any errors in your logs? If so could you share them? Thanks

**Comment by MrGoodGuy2144** [comment]
Oh man i am silly, It was an issue on my end. I should've inspected the logs better, i was a missing quotation or coma the line above so it makes sense it stopped working after adding that feed... I guess when i pasted that line it deleted it somehow :(

Sorry for the bother lol.

**Comment by MrGoodGuy2144** [comment]
Closed
