### ISSUE TITLE
Source author from feed item

### ISSUE THREAD

**Issue by eevui** [Qolors/FeedCord#28]
Currently, the author tag is sourced from the config file as evidenced here https://github.com/Qolors/FeedCord/blob/149cb87227bedba54b96787dfc47857c06f71b75/FeedCord/src/Services/DiscordPayloadService.cs#L33-L38 

However, some feeds actually provide an author/creator/source tag such as the Yahoo news RSS: https://www.yahoo.com/news/rss (uses `<source>`) or Notebookcheck's RSS feed: https://www.notebookcheck.net/News.152.100.html (uses `<dc:creator>`).

In my case, I want to be able to set the author field as the `<author>` tag of this feed: https://edge.pse.com.ph/companyPage/writeRss.do

It would be great if these can be configured to use a certain tag as the author field for the Discord embed.

**Comment by Qolors** [comment]
@eevui this was handled in the latest 2.1.1 update thanks to @xavier-hernandez  - please pull the latest image when you can. Cheers!
