### ISSUE TITLE
Request: Support for Github Atom RSS Feeds

### ISSUE THREAD

**Issue by LilDrunkenSmurf** [Qolors/FeedCord#3]
I'd love to use this on Github RSS feeds.

https://docs.github.com/en/rest/activity/feeds?apiVersion=2022-11-28
https://github.com/Qolors/FeedCord/commits/master/.atom

I tried setting this up, but logs showed issues with the format, as the browser automatically requests it in XML, but by default, timeline resources are returned in JSON. You can specify the `application/atom+xml` type in the Accept header to return timeline resources in Atom format.
```curl -H "Accept: application/atom+xml" https://github.com/Qolors/FeedCord/commits/master/.atom```

**Comment by Qolors** [comment]
Sure thing! I will have some free time tomorrow morning and will look in to this. Shouldn't be an issue to do this for you.

Keep you posted once more! :)

**Comment by Qolors** [comment]
Tested with the [1.3.0 Release](https://github.com/Qolors/FeedCord/releases/tag/v1.3.0), it properly handles parsing Github Atom Feeds.

If there are any unhandled issues please reach out - thanks!
