### ISSUE TITLE
ARM Image/Docker build

### ISSUE THREAD

**Issue by LilDrunkenSmurf** [Qolors/FeedCord#6]
I appreciate the v1.3.0 deployment. I did notice that `latest` was pushed, but `latest-arm` is still out of date (which is what I'm using).

I was curious if you mind sharing the dockerfile for the build, so I can build one myself?
I build a bunch of custom images and publish them to my ghcr here: https://github.com/LilDrunkenSmurf/containers

**Comment by Qolors** [comment]
Hi there! I have just updated the latest ARM image -  qolors/feedcord:latest-arm64

I have no problem sharing the docker build with you!
```
FROM --platform=linux/arm64 mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["FeedCord.csproj", "./"]
COPY ["src", "./src"]
RUN dotnet clean
RUN dotnet restore
RUN dotnet build -c Release -o /app/build
RUN dotnet publish -c Release -o /app/publish

FROM --platform=linux/arm64 mcr.microsoft.com/dotnet/aspnet:7.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "FeedCord.dll"]
```

This is ran with
`docker build -t <your-container-name> .`

For any future versions I will be sure to push the arm64 image as well :)

**Comment by LilDrunkenSmurf** [comment]
I created a pipeline to automatically build and push images whenever you make a new release:
<https://github.com/LilDrunkenSmurf/containers/commit/b85b9bc80565745d9db5ddbaf5078d31f10145f4>
<https://github.com/LilDrunkenSmurf/containers/actions/runs/7602202809>
<https://github.com/LilDrunkenSmurf/containers/pkgs/container/feedcord>

![image](https://github.com/Qolors/FeedCord/assets/46251616/05ba6d03-2280-44c4-aa15-19624ff9f2b2)

Thanks for sharing!

**Comment by Qolors** [comment]
This is awesome! Thanks for sharing as well :)
