### ISSUE TITLE
Forum Channel Posts

### ISSUE THREAD

**Issue by brianerdelyi** [Qolors/FeedCord#8]
How can I enable posts to a forum channel?  This requires the field "thread_name" in the body of the web hook.  This will create a post with that title.

Here is a screenshot of posts in a forum channel.

<img width="679" alt="2024-01-25_08-28-51" src="https://github.com/Qolors/FeedCord/assets/10991944/4628b5a1-1e07-4653-92db-16656ccf5f47">

When you open the post, users can comment and discuss it.

<img width="493" alt="2024-01-25_08-29-46" src="https://github.com/Qolors/FeedCord/assets/10991944/fbd752f1-aed2-47c6-be31-255e161df56b">

**Comment by Qolors** [comment]
Nice thought! Should be a straight forward implementation. This will be pushed out in the next release - it will be an addition to our config:
```
{
  "RssUrls": [
    "YOUR",
    "RSS URLS",
    "HERE"
  ],
  "YoutubeUrls": [
    "YOUR",
    "YOUTUBE CHANNEL URLS",
    "HERE",
    "eg. https://www.youtube.com/@IGN"
  ],
  "DiscordWebhookUrl": "https://discordapp.com/api/webhooks/1139357708546478200/ncB3dshJOPkQhthwOFQibeNt6YI-1_DiFbg0B3ZecfxchnbCGQNdG-m3PxqDdDSvt5Kk",
  "RssCheckIntervalMinutes": 3,
  "EnableAutoRemove": true,
  "Username": "FeedCord",
  "AvatarUrl": "https://i.imgur.com/1asmEAA.png",
  "AuthorIcon": "https://i.imgur.com/1asmEAA.png",
  "AuthorName": "FeedCord",
  "AuthorUrl": "https://github.com/Qolors/FeedCord",
  "FallbackImage": "https://i.imgur.com/f8M2Y5s.png",
  "FooterImage": "https://i.imgur.com/f8M2Y5s.png",
  "Color": 8411391,
  "DescriptionLimit": 200,
  "Forum": true
}
```

```
"Forum": true <----- This will enable "thread_name" to be sent in the payload. Defaulted to the post's title

**Comment by brianerdelyi** [comment]
That sounds like it will work.  looking forward to testing.  You wont believe that few other RSS to web hook tools support this.

**Comment by brianerdelyi** [comment]
I'm curious about a few items in the configuration:

  "EnableAutoRemove" - What does this do?

Are these fields mandatory?  What if they do not exist in the config?  The Webhook in Discord is configured with a username and avatar.

  "Username": "FeedCord",
  "AvatarUrl": "https://i.imgur.com/1asmEAA.png",
  "AuthorIcon": "https://i.imgur.com/1asmEAA.png",
  "AuthorName": "FeedCord",
  "AuthorUrl": "https://github.com/Qolors/FeedCord",

What if these fields do not exist in the config

  "FallbackImage": "https://i.imgur.com/f8M2Y5s.png",
  "FooterImage": "https://i.imgur.com/f8M2Y5s.png",


I have been using a web hook with the following data:
{
    "thread_name":"<title of the article>",
    "content":"<url of the article>"
}

Discord automatically embeds the content based on <url of the article>.  In some cases it might be useful to build this as an embed if Discord doesn't create it correctly.  We can start with your initial version and enhance though.

For example, here are two different posts.  One is me doing the sample above with postman and another is a bot named Readybot.  Readybot uses "Chess News" as the content and embeds the other information.  It's a subtle detail but it allows the title of the RSS feed to be on the tile of the forum post.  In my example, it shows url of the article.  Just a minor UX difference.  I'd love if I could even override the name of the RSS feed (since they aren't always useful).  Again, excited to test this initial version.

<img width="758" alt="2024-01-25_11-22-16" src="https://github.com/Qolors/FeedCord/assets/10991944/61d7dc99-2fb4-436e-b8b9-19fa11a4b4ec">

**Comment by Qolors** [comment]
> "EnableAutoRemove" - What does this do?

This will remove a URL from your list to stop processing it if it gets more than 3 bad responses from said URL

> Are these fields mandatory? What if they do not exist in the config? The Webhook in Discord is configured with a username and avatar.
> 
> "Username": "FeedCord", "AvatarUrl": "https://i.imgur.com/1asmEAA.png", "AuthorIcon": "https://i.imgur.com/1asmEAA.png", "AuthorName": "FeedCord", "AuthorUrl": "https://github.com/Qolors/FeedCord",

Right now they are mandatory - but I can fix this in the coming update (we would leave them as empty strings) example:
>"Username": ""

> What if these fields do not exist in the config
> 
> "FallbackImage": "https://i.imgur.com/f8M2Y5s.png", "FooterImage": "https://i.imgur.com/f8M2Y5s.png",

There's no handling to have a Config without these fields, but we can change these to be left blank as stated above.

> I have been using a web hook with the following data: { "thread_name":"<title of the article>", "content":"" }
> 
> Discord automatically embeds the content based on . In some cases it might be useful to build this as an embed if Discord doesn't create it correctly. We can start with your initial version and enhance though.
> For example, here are two different posts. One is me doing the sample above with postman and another is a bot named Readybot. Readybot uses "Chess News" as the content and embeds the other information. It's a subtle detail but it allows the title of the RSS feed to be on the tile of the forum post. In my example, it shows url of the article. Just a minor UX difference.

This is certainly doable - with the updated Config file having the forum set to True, we can alter the way we're sending the payload to Discord to get the desired result.

> I'd love if I could even override the name of the RSS feed (since they aren't always useful). ...

I could definitely implement this - simplest way would be something along the lines of this in our config:

```
"RssUrls": [
    { 
      "url": "the-rss-url",
      "name": "My Custom Name"
    },
  ]
```

**Comment by brianerdelyi** [comment]
You're amazing!  Let me just start with testing the "Thread_Name" feature.

Once that's working, I can jump in and create user stories for new features we discussed above (if you'd like).  All doable... just don't want to overwhelm you.  Please know people like me appreciate what you're doing.  This lets me avoid paying for an IFTTT or Zapier plan or even a premium bot.

**Comment by Qolors** [comment]
Right on! Appreciate the support! I'm glad it's finding good use 👍

**Comment by Qolors** [comment]
Hey there!

I have finished working on getting functionality for Forum Posts - like the idea!

please try running your docker container with the nightly image
> qolors/feedcord:nightly

Let me know your thoughts!

Reminder that you have to add the Forum field to your config:

```
{
  // ..Rest of Fields.. //
  "DescriptionLimit": 200,
  "Forum": true <--- Set this as true
}
```

Still have more work on the official release

**Comment by brianerdelyi** [comment]
FYI, I havent forgotten about you.  I hope to install everything tomorrow and see how it works.

**Comment by Qolors** [comment]
Hey there! Release 2.0.0 is out! 🎉

Forums Support is now available - some modifications to your config file will be required.. Read more [here](https://github.com/Qolors/FeedCord/releases/tag/v2.0.0)

Thanks for the support!
